name: CI

on: [push]

jobs:
  build_aws:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Verify Python syntax
      run: python3 -m py_compile lambda_function.py
      working-directory: aws/ec2
  build_gcp:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - uses: actions/checkout@v1
    - name: Get dependencies
      run: go get -v -d ./...
      working-directory: gcp/compute-engine
    - name: Go build
      run: go build -v .
      working-directory: gcp/compute-engine
